#!/bin/sh
# Xsetup - run as root before the login dialog appears

if [ -e /sbin/prime-offload ]; then
    echo running NVIDIA Prime setup /sbin/prime-offload
    /sbin/prime-offload
fi

# Make sddm display login-screen on one monitor
NUM=$(xrandr --listmonitors | awk '{print $4}' | grep -c .)
if [ "$NUM" -gt "1" ]; then
   CMD=$(xrandr --listmonitors | awk '{print $4}' | grep .)
   cnt=0
   for disp in $CMD; do
      if [ $cnt -gt 0 ]; then
         xrandr --output "$disp" --off
      fi
      cnt=$(( cnt + 1 ))
   done
fi
